modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "totemcounter"
displayName = "TotemCounter"
version = "${version}"

iconFile = "assets/totemcounter/icon.png"
authors = "uku"
description = "counts the amount of skill issues (totem pops)"
displayURL = "https://modrinth.com/project/T9R7YTnA"

[[dependencies.totemcounter]]
modId = "minecraft"
type = "required"
versionRange = "[26.3,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.totemcounter]]
modId = "neoforge"
type = "required"
versionRange = "[26.3.0.0-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.totemcounter]]
modId = "ukulib"
type = "required"
versionRange = "[2.2.0,3)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "totemcounter.mixins.json"